OARSMVC/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OARSMVC.Models;

namespace OARSMVC.Controllers
{
    public class GuestController : Controller
    {
        private OARSEntities db = new OARSEntities();

       
        // GET: Guest
        public ActionResult Index()
        {
            
            var origin = (from m in db.tblFlights
                         select m.FlightOrigin).Distinct();
            ViewBag.FlightOrigin = new SelectList(origin);

            var destination = (from m in db.tblFlights
                         select m.FlightDestination

           ).Distinct();
            ViewBag.FlightDestination = new SelectList(destination);
            return View(db.tblFlights.ToList());



        }
        //public ActionResult IndexSample()
        //{
        //    var origin = (from m in db.tblFlights
        //                  select m.FlightOrigin).Distinct();
        //    ViewBag.FlightOrigin = new SelectList(origin);

        //    var destination = (from m in db.tblFlights
        //                       select m.FlightDestination

        //   ).Distinct();
        //    ViewBag.FlightDestination = new SelectList(destination);
        //    return View(db.tblFlights.ToList());
        //}

        public ActionResult Search()
        {
            return View(db.tblFlights.ToList());
        }

        // GET: Guest/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Guest/Create
        public ActionResult Create()
        {
           
            List<tblFlight> flights = db.tblFlights.ToList();
            List<Guest> guests = db.Guests.ToList();

            //var flightnumber = (from f in db.tblFlights select f.FlightNumber).Where();  

            return View();
        }

        // POST: Guest/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "GuestName,GuestEmail,GuestPhoneNo,GuestAge,GuestGender")] Guest guest)
        {
            if (ModelState.IsValid)
            {
                db.Guests.Add(guest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(guest);
        }

        // GET: Guest/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Guest/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Guest/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Guest/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ConfirmBooking()
        {
            bool isChecked;
            return View();
        }

        public ActionResult TicketStatus()
        {
            var BookingPNR = db.tblBookings.Where(b => b.BookingRecord == 1).Select(b => b.BookingPNR).ToList();
            
            ViewBag.PNR = new SelectList(BookingPNR);
            return View(db.tblBookings.ToList());
           
        }
            
    }
}

OARSMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OARSMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

OARSMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OARSMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    CG-Airline<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OARSMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Online Airlines Reservation System";
}

<head>
    <style>
        h2 {
            margin: 1em 0 0.5em 0;
            color: #343434;
            font-weight: normal;
            font-family: 'Ultra', sans-serif;
            font-size: 36px;
            line-height: 42px;
            text-transform: uppercase;
            text-shadow: 0 2px white, 0 3px #777;
        }
        
        
    </style>
</head>
<body>

    <h2 style="background-color:aliceblue"><marquee>CG Airlines Reservation System</marquee></h2>
    <p></p>
    <div class="jumbotron">

        <p class="lead">CG Airlines Reservation System is a new state of the art reservation system that has built in class search features and best flying rates in the country </p>

    </div>
    <div class="row">
        <div class="col-md-4 jumbotron">
            <h2>Administrator</h2>
            <p>
                <ol>
                    <li>Login</li>
                    <li>Add new flights into the system</li>
                    <li>Flight Analysis Reports</li>
                    <li>Flight status Modification</li>
                </ol>
            </p>
            <p><b style="text-align:center">  @Html.ActionLink("Admin", "Index", "Guest", null, new { @style = "background-color:dodgerblue; color:white", @class = "ui-button img-rounded form-control" }) </b></p>
        </div>
        <div class="col-md-4">

        </div>
        <div class="col-md-4 jumbotron">
            <h2>Guest User</h2>
            <p>
                <ol>
                    <li>Search Flight</li>
                    <li>Book Flight</li>
                    <li>Cancel Flight</li>
                    <li>Check PNR and Flight Status</li>
                </ol>
            </p>
            <p><b style="text-align:center">  @Html.ActionLink("Guest User", "Index","Guest",null, new { @style = "background-color:dodgerblue; color:white", @class = "ui-button img-rounded form-control" }) </b></p>
        </div>
    </div>
    
    <div>
        <p>Administrator</p>
    </div>
</body>